2017-10-23T19:33:53.280Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '93b885adfe0da089cdf634904fd59f71' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-10-23T19:33:53.281Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '93b885adfe0da089cdf634904fd59f71' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '93b885adfe0da089cdf634904fd59f71' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-10-23T19:33:53.442Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '9e688c58a5487b8eaf69c9e1005ad0bf' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-10-23T19:33:53.442Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '9e688c58a5487b8eaf69c9e1005ad0bf' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '9e688c58a5487b8eaf69c9e1005ad0bf' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-10-23T19:33:55.225Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8666683506aacd900bbd5a74ac4edf68' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-10-23T19:33:55.225Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8666683506aacd900bbd5a74ac4edf68' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8666683506aacd900bbd5a74ac4edf68' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-10-23T19:33:55.290Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '06eca1b437c7904cc3ce6546c8110110' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-10-23T19:33:55.291Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '06eca1b437c7904cc3ce6546c8110110' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '06eca1b437c7904cc3ce6546c8110110' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-10-23T19:33:55.556Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '89e74e640b8c46257a29de0616794d5d' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-10-23T19:33:55.556Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '89e74e640b8c46257a29de0616794d5d' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '89e74e640b8c46257a29de0616794d5d' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-10-23T19:33:55.863Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8bb6c17838643f9691cc6a4de6c51709' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-10-23T19:33:55.863Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8bb6c17838643f9691cc6a4de6c51709' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8bb6c17838643f9691cc6a4de6c51709' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-10-23T19:33:55.894Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'ec7f7e7bb43742ce868145f71d37b53c' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-10-23T19:33:55.894Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'ec7f7e7bb43742ce868145f71d37b53c' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'ec7f7e7bb43742ce868145f71d37b53c' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-10-23T19:33:56.663Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '55a54008ad1ba589aa210d2629c1df41' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-10-23T19:33:56.664Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '55a54008ad1ba589aa210d2629c1df41' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '55a54008ad1ba589aa210d2629c1df41' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
