2017-10-27T16:48:54.789Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8bb6c17838643f9691cc6a4de6c51709' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-10-27T16:48:54.790Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8bb6c17838643f9691cc6a4de6c51709' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8bb6c17838643f9691cc6a4de6c51709' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
