2017-11-23T18:25:38.800Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '93b885adfe0da089cdf634904fd59f71' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:25:38.801Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '93b885adfe0da089cdf634904fd59f71' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '93b885adfe0da089cdf634904fd59f71' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:25:40.733Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8bb6c17838643f9691cc6a4de6c51709' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:25:40.733Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8bb6c17838643f9691cc6a4de6c51709' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8bb6c17838643f9691cc6a4de6c51709' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:25:43.380Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '55a54008ad1ba589aa210d2629c1df41' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:25:43.380Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '55a54008ad1ba589aa210d2629c1df41' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '55a54008ad1ba589aa210d2629c1df41' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:25:43.387Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '06eca1b437c7904cc3ce6546c8110110' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:25:43.387Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '06eca1b437c7904cc3ce6546c8110110' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '06eca1b437c7904cc3ce6546c8110110' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:25:45.783Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '89e74e640b8c46257a29de0616794d5d' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:25:45.784Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '89e74e640b8c46257a29de0616794d5d' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '89e74e640b8c46257a29de0616794d5d' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:25:45.785Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '5e732a1878be2342dbfeff5fe3ca5aa3' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:25:45.785Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '5e732a1878be2342dbfeff5fe3ca5aa3' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '5e732a1878be2342dbfeff5fe3ca5aa3' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:25:48.382Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'ec7f7e7bb43742ce868145f71d37b53c' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:25:48.382Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'ec7f7e7bb43742ce868145f71d37b53c' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'ec7f7e7bb43742ce868145f71d37b53c' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:25:51.316Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8666683506aacd900bbd5a74ac4edf68' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:25:51.316Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8666683506aacd900bbd5a74ac4edf68' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8666683506aacd900bbd5a74ac4edf68' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:25:57.157Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '9e688c58a5487b8eaf69c9e1005ad0bf' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:25:57.158Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '9e688c58a5487b8eaf69c9e1005ad0bf' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '9e688c58a5487b8eaf69c9e1005ad0bf' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:25:59.311Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'e2ba905bf306f46faca223d3cb20e2cf' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:25:59.311Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'e2ba905bf306f46faca223d3cb20e2cf' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'e2ba905bf306f46faca223d3cb20e2cf' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
