2017-11-23T18:39:55.041Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '6385caaa3b6d87ae851dd9f796c0ea69' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:39:55.043Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '6385caaa3b6d87ae851dd9f796c0ea69' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '6385caaa3b6d87ae851dd9f796c0ea69' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:39:57.737Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '6c7826631b2461a464cb6b92b9f90403' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:39:57.738Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '6c7826631b2461a464cb6b92b9f90403' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '6c7826631b2461a464cb6b92b9f90403' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:39:59.785Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '581196f156c4a265f07520850ca796ee' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:39:59.785Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '581196f156c4a265f07520850ca796ee' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '581196f156c4a265f07520850ca796ee' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:01.323Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8a03b1835a4ca1f5c30a007226df6e87' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:01.323Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8a03b1835a4ca1f5c30a007226df6e87' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8a03b1835a4ca1f5c30a007226df6e87' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:02.270Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'a61abca182394af36649ef11aab8a176' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:02.270Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'a61abca182394af36649ef11aab8a176' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'a61abca182394af36649ef11aab8a176' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:03.059Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '82afe0c3369284d076b9bc77714077f8' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:03.060Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '82afe0c3369284d076b9bc77714077f8' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '82afe0c3369284d076b9bc77714077f8' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:03.070Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '41551c9cfd7ba9a52c38040aa6945177' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:03.071Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '41551c9cfd7ba9a52c38040aa6945177' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '41551c9cfd7ba9a52c38040aa6945177' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:04.912Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'a68e54313b405840c028e070348c1ab6' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:04.912Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'a68e54313b405840c028e070348c1ab6' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'a68e54313b405840c028e070348c1ab6' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:05.018Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8519fb5acd6bf56f5a5e647704ecf370' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:05.019Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8519fb5acd6bf56f5a5e647704ecf370' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8519fb5acd6bf56f5a5e647704ecf370' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:05.735Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '1fa966557feec16d5d1d91fff3fee19f' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:05.735Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '1fa966557feec16d5d1d91fff3fee19f' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '1fa966557feec16d5d1d91fff3fee19f' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:06.555Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8c3434bfe3188948c5c3397e2ebb1d9f' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:06.555Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8c3434bfe3188948c5c3397e2ebb1d9f' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8c3434bfe3188948c5c3397e2ebb1d9f' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:06.952Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '685318a98bc338a99404265c2c736d41' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:06.952Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '685318a98bc338a99404265c2c736d41' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '685318a98bc338a99404265c2c736d41' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:07.488Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '5f0228c02185a0ace50f7adb44adfa6b' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:07.489Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '5f0228c02185a0ace50f7adb44adfa6b' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '5f0228c02185a0ace50f7adb44adfa6b' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:07.654Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'e4a4bbf19aeee78ea8b8b4ff4c2ff3c1' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:07.654Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'e4a4bbf19aeee78ea8b8b4ff4c2ff3c1' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'e4a4bbf19aeee78ea8b8b4ff4c2ff3c1' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:08.214Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'bbaf54db884d6e7ea9252c44ecb45f54' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:08.214Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'bbaf54db884d6e7ea9252c44ecb45f54' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'bbaf54db884d6e7ea9252c44ecb45f54' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:08.561Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8faa25098b7e252bc2e03373a480039e' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:08.561Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8faa25098b7e252bc2e03373a480039e' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8faa25098b7e252bc2e03373a480039e' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:09.231Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '0e24dc59f79432e187272e7acda01937' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:09.232Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '0e24dc59f79432e187272e7acda01937' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '0e24dc59f79432e187272e7acda01937' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:09.615Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'cb54cdda45424ea636fcfc4a594a1bd3' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:09.615Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'cb54cdda45424ea636fcfc4a594a1bd3' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'cb54cdda45424ea636fcfc4a594a1bd3' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:10.276Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '58a8bc17edd11cd37c7956823c5e6c3d' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:10.277Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '58a8bc17edd11cd37c7956823c5e6c3d' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '58a8bc17edd11cd37c7956823c5e6c3d' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:10.605Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'c38e41cf880623cec59807a858865ee9' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:10.606Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'c38e41cf880623cec59807a858865ee9' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'c38e41cf880623cec59807a858865ee9' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:11.082Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '810b54988f27f7f9f49b838e90a407b9' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:11.083Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '810b54988f27f7f9f49b838e90a407b9' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '810b54988f27f7f9f49b838e90a407b9' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:11.282Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '0324de4b2e3c4a0d60e9d76bb597d704' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:11.282Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '0324de4b2e3c4a0d60e9d76bb597d704' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '0324de4b2e3c4a0d60e9d76bb597d704' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:11.368Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '92a290f44786938eab3c6d108f22c0db' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:11.368Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '92a290f44786938eab3c6d108f22c0db' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '92a290f44786938eab3c6d108f22c0db' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:12.310Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '3f88bb252db8d09d4296a6539a75114c' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:12.310Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '3f88bb252db8d09d4296a6539a75114c' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '3f88bb252db8d09d4296a6539a75114c' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:12.356Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'df102a5f51aff008ee649aa7b1a27164' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:12.357Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'df102a5f51aff008ee649aa7b1a27164' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'df102a5f51aff008ee649aa7b1a27164' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:14.003Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '48485b6f4f5373601aba8d1a6b526cf7' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:14.003Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '48485b6f4f5373601aba8d1a6b526cf7' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '48485b6f4f5373601aba8d1a6b526cf7' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:15.167Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'c765b294837825690b7ad7fc60eccfcf' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:15.167Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'c765b294837825690b7ad7fc60eccfcf' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'c765b294837825690b7ad7fc60eccfcf' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:15.561Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'c1f14cfd5d4475b213937bd7a789e47d' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:15.561Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'c1f14cfd5d4475b213937bd7a789e47d' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'c1f14cfd5d4475b213937bd7a789e47d' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:16.302Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8226413bb31a152e68b0da2f4cab9188' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:16.303Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8226413bb31a152e68b0da2f4cab9188' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8226413bb31a152e68b0da2f4cab9188' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:16.884Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '0856719219b5cfb482ac1ed495287fa0' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:16.884Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '0856719219b5cfb482ac1ed495287fa0' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '0856719219b5cfb482ac1ed495287fa0' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:17.325Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '61fa7a30105863bf30291196961371e4' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:17.325Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '61fa7a30105863bf30291196961371e4' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '61fa7a30105863bf30291196961371e4' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:18.283Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'c3a5ddccecc60b3dfb53aadaf6c89d3c' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:18.283Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'c3a5ddccecc60b3dfb53aadaf6c89d3c' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'c3a5ddccecc60b3dfb53aadaf6c89d3c' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:18.330Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'dc01182b995bdc48aafa583b71ef5fe0' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:18.330Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'dc01182b995bdc48aafa583b71ef5fe0' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'dc01182b995bdc48aafa583b71ef5fe0' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:18.422Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '5304623f25069141dae627bf871d758b' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:18.422Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '5304623f25069141dae627bf871d758b' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '5304623f25069141dae627bf871d758b' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:18.656Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '3bd142a8d43e2083c631f54748970122' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:18.656Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '3bd142a8d43e2083c631f54748970122' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '3bd142a8d43e2083c631f54748970122' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:18.673Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '50fb81f2b325dc3435ffd1d6ff8941c0' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:18.673Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '50fb81f2b325dc3435ffd1d6ff8941c0' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '50fb81f2b325dc3435ffd1d6ff8941c0' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:19.015Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'a28212251026f0fc95a50e699e0bbf52' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:19.015Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'a28212251026f0fc95a50e699e0bbf52' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'a28212251026f0fc95a50e699e0bbf52' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:19.912Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'b8a039b30f6618392f6d570e67f3b241' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:19.913Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'b8a039b30f6618392f6d570e67f3b241' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'b8a039b30f6618392f6d570e67f3b241' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:20.967Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'c2c2055d0aceb4ee059add9c8aadfec3' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:20.967Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'c2c2055d0aceb4ee059add9c8aadfec3' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'c2c2055d0aceb4ee059add9c8aadfec3' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:21.323Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'f3f24c811ba724fac11193f751956449' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:21.324Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'f3f24c811ba724fac11193f751956449' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'f3f24c811ba724fac11193f751956449' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:21.701Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'a60e28bc14b6a028f7c50efe0e03c669' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:21.701Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'a60e28bc14b6a028f7c50efe0e03c669' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'a60e28bc14b6a028f7c50efe0e03c669' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:22.311Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '9455c17249f09a3b66ea273c4e7d5310' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:22.311Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '9455c17249f09a3b66ea273c4e7d5310' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '9455c17249f09a3b66ea273c4e7d5310' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:23.380Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'fca7372468fa0e0689f54cd21fd653be' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:23.380Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'fca7372468fa0e0689f54cd21fd653be' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'fca7372468fa0e0689f54cd21fd653be' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:24.317Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'b7bdb034ef8ce93fa3a8d16b458bce86' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:24.318Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'b7bdb034ef8ce93fa3a8d16b458bce86' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'b7bdb034ef8ce93fa3a8d16b458bce86' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:24.674Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '361e265bca93633a1fbafde0d2d42b72' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:24.674Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '361e265bca93633a1fbafde0d2d42b72' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '361e265bca93633a1fbafde0d2d42b72' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:25.079Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'fcd0e945e738c436e98e256284ff9a96' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:25.080Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'fcd0e945e738c436e98e256284ff9a96' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'fcd0e945e738c436e98e256284ff9a96' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:25.081Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'ef39ff9463b6073de83cfca3d85def5a' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:25.081Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'ef39ff9463b6073de83cfca3d85def5a' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'ef39ff9463b6073de83cfca3d85def5a' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:25.428Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '2e63d75cdbd02e920cf2f8ea3859da09' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:25.428Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '2e63d75cdbd02e920cf2f8ea3859da09' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '2e63d75cdbd02e920cf2f8ea3859da09' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:25.512Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '26eb3922f3d8f54f63d222e0f741014f' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:25.512Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '26eb3922f3d8f54f63d222e0f741014f' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '26eb3922f3d8f54f63d222e0f741014f' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:25.568Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'a3b577f5d19e7316b83205be33340d16' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:25.569Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'a3b577f5d19e7316b83205be33340d16' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'a3b577f5d19e7316b83205be33340d16' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:27.571Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'f7c57f06a1d3ce117749fc98e2111668' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:27.572Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'f7c57f06a1d3ce117749fc98e2111668' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'f7c57f06a1d3ce117749fc98e2111668' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:27.574Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'b4ba74af6b068d53ed848a43ea68d767' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:27.574Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'b4ba74af6b068d53ed848a43ea68d767' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'b4ba74af6b068d53ed848a43ea68d767' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:27.769Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '5c8a55787a4d331446b145f21758f990' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:27.769Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '5c8a55787a4d331446b145f21758f990' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '5c8a55787a4d331446b145f21758f990' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:28.029Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'f689ed86addcc5058fb9d20351c5edce' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:28.030Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'f689ed86addcc5058fb9d20351c5edce' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'f689ed86addcc5058fb9d20351c5edce' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:30.439Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '85c66f54331d1fe689e9a1c761a53423' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:30.439Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '85c66f54331d1fe689e9a1c761a53423' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '85c66f54331d1fe689e9a1c761a53423' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:30.603Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'dfcb813d6c003fb3e2fca9f5295e9f58' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:30.603Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'dfcb813d6c003fb3e2fca9f5295e9f58' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'dfcb813d6c003fb3e2fca9f5295e9f58' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:30.614Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '2fd9d0f622bab4400a22124f4a09a39d' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:30.614Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '2fd9d0f622bab4400a22124f4a09a39d' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '2fd9d0f622bab4400a22124f4a09a39d' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:30.644Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '005d3c812c2c037e9b0b48c0bf1b642a' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:30.644Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '005d3c812c2c037e9b0b48c0bf1b642a' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '005d3c812c2c037e9b0b48c0bf1b642a' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:31.115Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'b45f432ab28d3501db17cf5b508ec8a4' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:31.115Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'b45f432ab28d3501db17cf5b508ec8a4' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'b45f432ab28d3501db17cf5b508ec8a4' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:33.136Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'e2762d55e50742af2beba62da2122577' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:33.136Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'e2762d55e50742af2beba62da2122577' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'e2762d55e50742af2beba62da2122577' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:33.139Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8374f96cc135bee7c02d129fba5d6dfb' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:33.139Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8374f96cc135bee7c02d129fba5d6dfb' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8374f96cc135bee7c02d129fba5d6dfb' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:33.228Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '6d13541d2cedd620921d41aece9c01d3' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:33.228Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '6d13541d2cedd620921d41aece9c01d3' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '6d13541d2cedd620921d41aece9c01d3' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:33.329Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'a83e33f5146fae45dcc9ca6c38760bb2' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:33.329Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'a83e33f5146fae45dcc9ca6c38760bb2' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'a83e33f5146fae45dcc9ca6c38760bb2' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:33.380Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '90d568d358c32363d4e729e093eecb6c' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:33.380Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '90d568d358c32363d4e729e093eecb6c' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '90d568d358c32363d4e729e093eecb6c' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:35.714Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '479bccfed3b4ebb048e9e431e677f1a3' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:35.714Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '479bccfed3b4ebb048e9e431e677f1a3' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '479bccfed3b4ebb048e9e431e677f1a3' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:35.817Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '4a30a71a1a053495d692dba4db5b3361' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:35.818Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '4a30a71a1a053495d692dba4db5b3361' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '4a30a71a1a053495d692dba4db5b3361' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:37.787Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'a832edf87f4121e9c3b829eb0c194cce' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:37.787Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'a832edf87f4121e9c3b829eb0c194cce' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'a832edf87f4121e9c3b829eb0c194cce' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:37.919Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '32649384730b2d61c9e79d46de589115' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:37.919Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '32649384730b2d61c9e79d46de589115' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '32649384730b2d61c9e79d46de589115' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:37.960Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '07d4f780e3528db8c539ee5c21fddeae' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:37.960Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '07d4f780e3528db8c539ee5c21fddeae' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '07d4f780e3528db8c539ee5c21fddeae' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:39.638Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '41e8a8fdd1be8d07fcbe328dd009ca2e' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:39.638Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '41e8a8fdd1be8d07fcbe328dd009ca2e' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '41e8a8fdd1be8d07fcbe328dd009ca2e' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:41.623Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '73d0a7b3fab51beeee8ba428b9cd1d47' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:41.623Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '73d0a7b3fab51beeee8ba428b9cd1d47' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '73d0a7b3fab51beeee8ba428b9cd1d47' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:41.734Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '64e42751031c29a8b5b2a3031508e6c9' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:41.734Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '64e42751031c29a8b5b2a3031508e6c9' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '64e42751031c29a8b5b2a3031508e6c9' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:41.839Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '9b0c9e02ce58f812e9d63ec6f3cfb297' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:41.839Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '9b0c9e02ce58f812e9d63ec6f3cfb297' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '9b0c9e02ce58f812e9d63ec6f3cfb297' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:43.898Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'f3040fcb274d572933acbea14d710c12' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:43.898Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'f3040fcb274d572933acbea14d710c12' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'f3040fcb274d572933acbea14d710c12' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:44.151Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '3380309c7bd60dd52c4db33d50dc501f' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:44.151Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '3380309c7bd60dd52c4db33d50dc501f' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '3380309c7bd60dd52c4db33d50dc501f' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:44.186Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '31540cf0b21cd8513d3dbc7192d8cad1' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:44.187Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '31540cf0b21cd8513d3dbc7192d8cad1' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '31540cf0b21cd8513d3dbc7192d8cad1' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:44.295Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '3ea2bb821ba551296e5a77caa88a523f' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:44.295Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '3ea2bb821ba551296e5a77caa88a523f' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '3ea2bb821ba551296e5a77caa88a523f' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:44.386Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'dd75ec426c36356afd6a9987a175824b' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:44.387Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'dd75ec426c36356afd6a9987a175824b' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'dd75ec426c36356afd6a9987a175824b' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:44.500Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8a7ea3516f353de45b95b4c3317f3c69' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:44.501Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8a7ea3516f353de45b95b4c3317f3c69' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8a7ea3516f353de45b95b4c3317f3c69' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:44.607Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'c3eecd083c0f4827f526059b03b75e4c' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:44.607Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'c3eecd083c0f4827f526059b03b75e4c' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'c3eecd083c0f4827f526059b03b75e4c' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:46.480Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'b55df7fe0d0ec6e9d3c3d74a06f4faf1' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:46.480Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'b55df7fe0d0ec6e9d3c3d74a06f4faf1' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'b55df7fe0d0ec6e9d3c3d74a06f4faf1' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:46.508Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '9182bc7e4b9b35047ace494d28614fe6' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:46.508Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '9182bc7e4b9b35047ace494d28614fe6' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '9182bc7e4b9b35047ace494d28614fe6' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:46.633Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '9ed4a12cf365a4e7f4569fee07c1e276' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:46.634Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '9ed4a12cf365a4e7f4569fee07c1e276' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '9ed4a12cf365a4e7f4569fee07c1e276' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:46.648Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56a2f807fb2b733d04da71743468df5f' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:46.648Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56a2f807fb2b733d04da71743468df5f' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56a2f807fb2b733d04da71743468df5f' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:46.847Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '784fd054301106e1679454fc0e7d9217' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:46.848Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '784fd054301106e1679454fc0e7d9217' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '784fd054301106e1679454fc0e7d9217' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:48.267Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '6264a30ebd7d7c8e62f4981f64601d33' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:48.267Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '6264a30ebd7d7c8e62f4981f64601d33' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '6264a30ebd7d7c8e62f4981f64601d33' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:48.335Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '70f24df82b635129b05e909f1252a2fb' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:48.335Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '70f24df82b635129b05e909f1252a2fb' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '70f24df82b635129b05e909f1252a2fb' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:48.496Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'bf953887c553c1553e0ffd9ccfc8ed24' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:48.497Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'bf953887c553c1553e0ffd9ccfc8ed24' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'bf953887c553c1553e0ffd9ccfc8ed24' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:48.516Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '75354c5ccb5ca15e9ac5957ac0eee120' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:48.517Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '75354c5ccb5ca15e9ac5957ac0eee120' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '75354c5ccb5ca15e9ac5957ac0eee120' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:50.230Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'eceee32f271b90ef127d9c7adf224fb3' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:50.230Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'eceee32f271b90ef127d9c7adf224fb3' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'eceee32f271b90ef127d9c7adf224fb3' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:50.314Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8030b3dcdd08a28c2aaca1d6ea25053d' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:50.314Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8030b3dcdd08a28c2aaca1d6ea25053d' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8030b3dcdd08a28c2aaca1d6ea25053d' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:50.397Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '0ea0b11e51419f26a0f7b99c971629ea' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:50.397Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '0ea0b11e51419f26a0f7b99c971629ea' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '0ea0b11e51419f26a0f7b99c971629ea' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:50.450Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '09347d2b5d17a91e1e71347b0f779963' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:50.450Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '09347d2b5d17a91e1e71347b0f779963' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '09347d2b5d17a91e1e71347b0f779963' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:52.390Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '03e8c00dea408b2002f87f55eb0154d3' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:52.390Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '03e8c00dea408b2002f87f55eb0154d3' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '03e8c00dea408b2002f87f55eb0154d3' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:52.408Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '4b402790848b9196b6771ad6cd44937b' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:52.408Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '4b402790848b9196b6771ad6cd44937b' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '4b402790848b9196b6771ad6cd44937b' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:52.424Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '0438d18c0062af489e7a95ada8769f7e' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:52.424Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '0438d18c0062af489e7a95ada8769f7e' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '0438d18c0062af489e7a95ada8769f7e' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:52.432Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'a9dbd9f32ca0f65d3132adac27137447' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:52.432Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'a9dbd9f32ca0f65d3132adac27137447' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'a9dbd9f32ca0f65d3132adac27137447' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:52.521Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'd0ef81942a79596af5990216e3d17b4e' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:52.522Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'd0ef81942a79596af5990216e3d17b4e' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'd0ef81942a79596af5990216e3d17b4e' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:53.958Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'f67eebe778016abf6bd4529bd0adeac3' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:53.959Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'f67eebe778016abf6bd4529bd0adeac3' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'f67eebe778016abf6bd4529bd0adeac3' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
2017-11-23T18:40:53.997Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8e9387cf50cd5b93fed7855dc47fc450' as the object already exists)
    at /Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:434:17 {}$
2017-11-23T18:40:53.997Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8e9387cf50cd5b93fed7855dc47fc450' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID '8e9387cf50cd5b93fed7855dc47fc450' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/Users/a01334390/Documents/Git Projects/Lyra/Composer-Lyra/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:837:34)\n    at <anonymous>"}$
